import { certifications, certKey, isAvailable } from "./certifications";

export type CareerSkill = { name: string; aliases: string[] };
export type CareerPath = {
  id: string; title: string; group: string; tagline: string; search: string[];
  skills: CareerSkill[]; topics: [string, string, string, string];
  project: string; interviews: [string, string][]; certs: string[];
  credentialAdvice: string; learning: { label: string; url: string }[];
};
const skill = (text: string): CareerSkill => { const [name, ...aliases] = text.split("|"); return { name, aliases: [name, ...aliases] }; };
function path(id: string, title: string, group: string, tagline: string, skills: string[], topics: CareerPath["topics"], project: string, interviews: CareerPath["interviews"], certs: string[], search: string[], credentialAdvice = "Pick one credential that matches the technology in your target vacancies. Check prerequisites and prove the skills with a project before booking.", learning: CareerPath["learning"] = []): CareerPath {
  return { id, title, group, tagline, skills: skills.map(skill), topics, project, interviews, certs, search, credentialAdvice, learning };
}
export const careerPaths: CareerPath[] = [
  path("sap-sd", "SAP SD Consultant", "SAP & ERP", "Turn order-to-cash knowledge into a clear consulting story.",
    ["SAP S/4HANA|S4HANA|S/4HANA|S4 HANA", "Order to cash|order-to-cash|OTC|O2C", "Pricing|condition technique", "Master data|business partner|customer master", "Delivery|shipping|PGI", "Billing|invoice|invoicing", "Configuration|customizing|customising", "Integration|IDoc|FI-MM", "Testing|UAT|test cases", "Support|incident|troubleshooting"],
    ["Map sales organisations, distribution channels, divisions, plants and shipping points. Explain business partner and material master dependencies; trace enquiry → quotation → order → delivery → goods issue → billing.", "Practise sales document types, item categories, schedule lines, copy control and partner determination. Build pricing conditions and explain access sequences, condition records, taxes, discounts and missing-price diagnosis.", "Work through availability checks, delivery scheduling, picking and PGI, billing blocks, returns and credit scenarios. Trace FI account determination and MM dependencies; explain one IDoc failure and how you would coordinate with a technical team.", "Document a small sales process in an authorised practice system. Include configuration rationale, positive and negative UAT cases, screenshots without client data, an issue log and a release checklist. Rehearse explaining your own contribution."],
    "Build a domestic order-to-cash case: two customer types, a discount rule, one partial delivery, billing and a return. Deliver a process map, configuration notes, 10 test cases and two defect investigations. Label practice work as a lab, not a client implementation.",
    [["An order has no price. Where do you start?", "Check pricing procedure determination, condition records and validity, access sequence results and document/item data. Explain how you isolate the cause before changing configuration."], ["Why can an order be created but a delivery cannot?", "Investigate confirmed quantity and dates, shipping-point determination, delivery relevance, blocks and incompletion. Use document flow and messages as evidence."], ["Billing succeeds but the accounting document fails. What next?", "Read the exact posting error; inspect account determination and relevant master/configuration data with FI. Describe a controlled fix and retest."], ["How is an S/4HANA switch different from memorising ECC transactions?", "Discuss business partner data, Fiori workflows and the actual deployment edition. Separate public-cloud configuration from private-edition/on-premise customising."], ["How would you handle a change to a live pricing rule?", "Clarify effective dates and business impact, reproduce in a test system, test existing and new orders, obtain approval and document transport/release and rollback considerations."], ["You have support experience, not implementation experience. How do you present it?", "Explain the incidents, root causes, configuration changes, tests and stakeholder decisions you actually owned. Do not relabel support work as an end-to-end implementation."]],
    ["sap/s4hana-sales"], ["sap sd", "sap sales", "order to cash", "s/4hana sales", "otc consultant"],
    "For private-edition or on-premise SAP SD roles, consider SAP’s S/4HANA Sales implementation credential (C_TS462). Public-edition roles use a different scope: confirm the exact edition in the vacancy and SAP catalogue. Certification supports your evidence; it does not replace project experience.",
    [{ label: "SAP Sales learning journey", url: "https://learning.sap.com/learning-journeys/implementing-sales-in-sap-s-4hana-cloud-private-edition" }]),
  path("sap-mm", "SAP MM Consultant", "SAP & ERP", "Connect procurement, inventory and finance processes.",
    ["SAP MM|materials management", "SAP S/4HANA|S/4HANA|S4HANA", "Procurement|purchase order|procure-to-pay|P2P", "Inventory|goods receipt", "Master data|material master|supplier", "Invoice verification|MIRO", "Configuration|customizing", "Testing|UAT"],
    ["Map purchasing organisations, plants and storage locations; explain material and supplier master data.", "Trace requisition, sourcing, purchase order, release, goods receipt and invoice verification. Explain tolerances and approval controls.", "Practise stock transfers, returns, valuation and FI integration. Diagnose quantity and price differences with document evidence.", "Create a procurement case, configuration log and UAT pack. Explain the deployment edition and the process decisions you owned."],
    "Document a procure-to-pay lab with a partial receipt, invoice mismatch, return and stock transfer. Include expected stock and accounting effects.",
    [["The invoice is blocked. How do you investigate?", "Compare PO, goods receipt and invoice quantities/prices, tolerance settings and the specific block reason."], ["How do you explain a stock discrepancy?", "Trace movement history, stock type, valuation and timing; propose an authorised correction and reconciliation."]], [], ["sap mm", "sap procurement", "sap materials", "sourcing procurement"],
    "Choose the SAP S/4HANA Sourcing and Procurement credential for your target deployment edition. Use the current SAP catalogue to confirm its live assessment and registration requirements; do not book an old exam code from a vacancy.", [{ label: "Find the current SAP procurement credential", url: "https://learning.sap.com/certifications" }]),
  path("sap-fico", "SAP FI/CO Consultant", "SAP & ERP", "Translate finance processes into testable SAP solutions.",
    ["SAP FI|SAP FICO|FI/CO", "General ledger|GL accounting", "Accounts payable|AP accounting", "Accounts receivable|AR accounting", "Asset accounting|fixed assets", "Controlling|cost center|cost centre", "Period close|month-end|year-end", "Integration|MM|SD"],
    ["Review accounting foundations, company codes, chart of accounts, fiscal periods and financial master data.", "Trace GL, payables, receivables and asset transactions. Explain reconciliation and document controls.", "Practise period-close checks, reporting, cost/profit centre basics and MM/SD integration; distinguish FI scope from CO specialisation.", "Build a finance scenario with opening data, postings, reconciliation and a close checklist. Explain a defect using business and accounting language."],
    "Create a small-company finance lab covering a vendor invoice, customer receipt, asset acquisition and close reconciliation. Record assumptions and posting effects.",
    [["A sales invoice cannot post to FI. What do you check?", "Start with the error and document data, then account determination, master data and posting-period controls in coordination with SD."], ["How do you demonstrate close readiness?", "Describe reconciliations, unresolved items, asset/ledger checks, ownership and documented sign-off."]], [], ["sap fico", "sap fi", "sap co", "sap finance"],
    "Match Financial Accounting or Management Accounting certification to the role and deployment edition. FI and CO are related but have different scopes; use SAP’s current catalogue before booking.", [{ label: "SAP Financial Accounting learning journey", url: "https://learning.sap.com/learning-journeys/implementing-financial-accounting-in-sap-s-4hana" }, { label: "SAP certification catalogue", url: "https://learning.sap.com/certifications" }]),
  path("sap-abap", "SAP ABAP Developer", "SAP & ERP", "Build maintainable extensions and explain your technical decisions.",
    ["ABAP", "Object oriented ABAP|ABAP OO|OOP", "CDS|core data services", "RAP|RESTful application programming", "OData", "Debugging|debugger", "Performance|SQL trace", "Testing|ABAP unit"],
    ["Practise ABAP syntax, internal tables, classes, exceptions and database access with small, tested programs.", "Build CDS views and an API or business object. Learn RAP, authorisations and Fiori/OData integration for the target stack.", "Diagnose correctness and performance using debugging and traces. Explain released APIs, clean-core constraints and transport practices.", "Publish a sanitised code sample, unit tests and design notes. Be ready to compare classic ABAP and ABAP Cloud restrictions."],
    "Build a small business object with validation, authorisation and an OData service; include unit tests and one measured performance investigation.",
    [["A report is slow. How do you locate the bottleneck?", "Measure first; inspect database access, repeated queries and internal-table operations, then compare before/after behaviour."], ["How do you make an extension upgrade-friendly?", "Discuss released interfaces, separation from standard code, tests and the target system’s extensibility model."]], [], ["abap", "sap developer", "rap developer"],
    "Look for SAP’s current ABAP Cloud back-end developer certification when that stack matches the vacancy. Check SAP’s live catalogue for the current title and assessment; classic ABAP experience still needs role-specific evidence.", [{ label: "SAP developer learning and certifications", url: "https://learning.sap.com/certifications" }]),
  path("sap-integration", "SAP Integration Developer", "SAP & ERP", "Connect enterprise systems with observable, secure integrations.",
    ["SAP Integration Suite|SAP CPI|cloud integration", "iFlow|integration flow", "API|REST|SOAP", "Mapping|message mapping", "OAuth|authentication", "Groovy", "Monitoring|message monitoring", "IDoc"],
    ["Review HTTP, XML/JSON, authentication and synchronous versus asynchronous messaging.", "Build Integration Suite flows with adapters, mappings, routing and externalised configuration.", "Handle retries, idempotency, secrets and failure queues; diagnose messages using monitoring without exposing business data.", "Deploy a tested integration with an API contract, failure scenarios and operational runbook."],
    "Connect a sample order API to a mock fulfilment service. Demonstrate mapping, authentication, duplicate handling and recovery after a simulated outage.",
    [["A receiver times out. How do you prevent duplicate orders?", "Explain correlation IDs, idempotency, retry limits and reconciliation."], ["An integration works in test but fails in production. What evidence do you gather?", "Compare endpoints, credentials, certificates, connectivity and payload differences using redacted logs."]], ["sap/integration-developer"], ["sap cpi", "sap integration", "integration suite"], undefined, [{ label: "SAP Integration Developer preparation", url: "https://learning.sap.com/certifications/sap-certified-associate-integration-developer" }]),
  path("data-engineer", "Data Engineer", "Data & AI", "Build reliable pipelines, then show how they recover.", ["SQL", "Python", "ETL|ELT|data pipeline", "Spark|PySpark", "Data modelling|data modeling", "Orchestration|Airflow|ADF", "Data quality|validation", "Cloud|AWS|Azure|GCP|Databricks"], ["Practise SQL joins, windows, incremental loads and Python transformations; explain grain and data models.", "Build batch ingestion, transformations and orchestration on one target platform. Handle late and duplicate data.", "Add quality checks, access controls, partitioning, cost monitoring and recovery from failed runs.", "Publish a pipeline diagram, tests and runbook. Explain throughput and correctness with measured lab results."], "Build an incremental order pipeline with deduplication, quality checks, a reporting model and a backfill demonstration.", [["How do you safely rerun a failed pipeline?", "Explain checkpoints, idempotent writes, partition scope and validation."], ["A Spark job became slow. What do you inspect?", "Investigate skew, shuffles, file sizes and the execution plan before changing resources."]], ["databricks/data-engineer-associate", "microsoft/fabric-data-engineer", "aws/data-engineer-associate", "databricks/data-engineer-professional"], ["data engineer", "data engineering", "etl developer", "pyspark", "databricks"]),
  path("data-analyst", "Data Analyst", "Data & AI", "Turn clean data into decisions stakeholders can explain.", ["SQL", "Excel|spreadsheets", "Power BI|Tableau", "Data modelling|data modeling", "DAX|calculated measures", "Statistics|statistical", "Data quality|validation", "Stakeholders|business requirements"], ["Practise SQL, spreadsheets and basic statistics with a business dataset.", "Define metrics and build a clean model with explicit grain, relationships and date handling.", "Create a dashboard with accessible charts, drilldowns and quality checks; reconcile numbers to source.", "Present three decisions the analysis supports, including limitations and a concise stakeholder narrative."], "Analyse order profitability and returns. Produce a SQL model, metric dictionary and dashboard with three recommendations supported by data.", [["Two dashboards disagree. What do you check?", "Compare definitions, filters, refresh time, joins and grain before deciding which is correct."], ["A stakeholder asks for every metric on one page. How do you respond?", "Clarify the decision, prioritise measures and propose progressive detail."]], ["microsoft/power-bi-data-analyst", "databricks/data-analyst-associate", "salesforce/tableau-data-analyst"], ["data analyst", "bi analyst", "power bi", "tableau", "business intelligence"]),
  path("ai-engineer", "AI & GenAI Engineer", "Data & AI", "Move from a prompt demo to a tested AI application.", ["Python|TypeScript", "API|SDK", "RAG|retrieval augmented", "Embeddings|vector search", "Evaluation|evals", "Agents|tool calling", "Security|prompt injection", "Monitoring|observability"], ["Build an API application and understand model inputs, outputs, tokens and structured responses.", "Implement retrieval with document permissions, chunking and citations; add tool use only where needed.", "Create evaluation cases for correctness, refusal, injection and leakage. Track latency and cost.", "Deploy a small assistant with a human escalation route and documented failure cases."], "Build a policy assistant over public documents with citations, access boundaries and a versioned evaluation set.", [["How do you know a RAG change helped?", "Compare retrieval and answer evaluations on representative cases, including regressions and cost."], ["A retrieved document contains malicious instructions. What do you do?", "Treat retrieved text as untrusted data, restrict tools and test injection scenarios."]], ["microsoft/azure-ai-apps-agents", "databricks/generative-ai-engineer", "aws/generative-ai-developer", "anthropic/claude-developer-foundations"], ["ai engineer", "genai", "generative ai", "llm engineer", "rag engineer"], "Choose the cloud and application stack your target employer uses. Claude certifications currently require partner access; public Claude learning is a separate option. Check every exam’s current availability."),
  path("ml-engineer", "Machine Learning Engineer", "Data & AI", "Show the full model lifecycle, including production failures.", ["Python", "Machine learning|scikit-learn|PyTorch", "Statistics", "Feature engineering", "MLflow|experiment tracking", "Deployment|model serving", "Monitoring|drift", "CI/CD|MLOps"], ["Review validation, leakage, baselines, metrics and reproducible data splits.", "Build feature and training pipelines with experiment tracking and versioned artefacts.", "Deploy a model with tests, drift monitoring and a rollback plan; explain offline versus online metrics.", "Write a model card and demonstrate one failure investigation, including fairness and data limitations."], "Deploy a tabular prediction model with a baseline, reproducible training, serving endpoint and drift simulation.", [["Offline accuracy is high but production results are poor. Why?", "Investigate leakage, distribution shift, training-serving skew and whether the metric matches the business goal."], ["When would you retrain?", "Define monitoring thresholds, validation gates and rollback criteria rather than retraining blindly."]], ["databricks/machine-learning-associate", "aws/machine-learning-engineer", "google-cloud/professional-ml-engineer"], ["machine learning engineer", "ml engineer", "mlops", "machine learning"]),
  path("cloud-engineer", "Cloud Engineer", "Cloud & Engineering", "Operate secure infrastructure and explain how it stays available.", ["Linux|Windows Server", "Networking|VPC|VNet", "IAM|identity|RBAC", "Cloud|AWS|Azure|GCP", "Terraform|infrastructure as code", "Monitoring|CloudWatch", "Backup|recovery", "Scripting|Bash|PowerShell"], ["Build foundations in operating systems, networking, identity and one cloud provider.", "Deploy compute, storage and a private network with least-privilege access using code.", "Add monitoring, backups, patching and cost controls. Test a restore and a network failure.", "Document architecture and operating procedures, then explain a troubleshooting case end to end."], "Deploy a private web service with IAM, infrastructure as code, monitoring and a demonstrated backup restore.", [["A service is unreachable. What is your diagnostic order?", "Check scope, DNS, routes, firewall/security rules, service health and recent changes."], ["How do you prove backups work?", "Restore to an isolated environment and compare recovery time and integrity against stated objectives."]], ["microsoft/azure-administrator", "aws/cloudops-engineer", "google-cloud/associate-cloud-engineer"], ["cloud engineer", "cloud administrator", "azure administrator", "cloud operations"]),
  path("cloud-architect", "Cloud Architect", "Cloud & Engineering", "Make architecture trade-offs visible and defensible.", ["Architecture|solution design", "Cloud|AWS|Azure|GCP", "Networking", "Security|IAM", "Resilience|high availability", "Disaster recovery|RTO|RPO", "Cost|FinOps", "Stakeholders"], ["Gather functional needs, constraints, data classifications and non-functional requirements.", "Compare compute, data, networking and integration options with explicit trade-offs.", "Design identity, resilience, recovery and cost controls; test important assumptions.", "Present a decision record and migration plan with risks, ownership and measurable acceptance criteria."], "Design a resilient order platform with an architecture diagram, cost assumptions, recovery plan and five decision records.", [["A client asks for zero downtime at minimum cost. What do you do?", "Clarify actual business impact and service objectives, then compare realistic availability/cost options."], ["How would you plan a migration?", "Explain dependencies, waves, data consistency, validation, cutover and rollback."]], ["aws/solutions-architect-associate", "google-cloud/professional-cloud-architect", "microsoft/azure-solutions-architect", "aws/solutions-architect-professional"], ["cloud architect", "solutions architect", "azure architect", "aws architect"], "Start with architecture fundamentals and implementation evidence. Senior credentials are useful after real design experience; check prerequisite credentials such as Azure Administrator for Microsoft’s architect award."),
  path("devops", "DevOps & SRE Engineer", "Cloud & Engineering", "Automate delivery without losing reliability.", ["Linux", "CI/CD|GitHub Actions|Jenkins", "Docker|containers", "Kubernetes|K8s", "Terraform", "Monitoring|Prometheus|observability", "Scripting|Python|Bash", "SLO|incident response"], ["Practise Linux, Git, scripting and networking; automate a repeatable environment setup.", "Create a container build and CI/CD pipeline with tests, security checks and infrastructure as code.", "Add health probes, observability and service objectives; exercise deployment rollback and incident response.", "Document an incident simulation with a timeline, root cause and follow-up improvements."], "Ship an application through a tested pipeline with a staged release, alerting, rollback and an SLO dashboard.", [["A deployment increases errors. What happens next?", "Assess impact, stop rollout, mitigate or roll back, communicate and preserve evidence."], ["An alert fires every night without user impact. What do you change?", "Review the service objective, signal quality and thresholds; reduce noise without hiding real failures."]], ["hashicorp/terraform-associate", "linux-foundation/cka", "aws/devops-engineer-professional", "microsoft/devops-expert"], ["devops", "site reliability", "sre", "platform engineer"]),
  path("software-developer", "Software Developer", "Cloud & Engineering", "Present working software, tests and clear design choices.", ["Programming|Java|Python|TypeScript|C#", "API|REST", "SQL|database", "Git", "Testing|unit tests", "Authentication|OAuth", "CI/CD", "Debugging"], ["Practise your target language, data structures, Git and readable code.", "Build an API and database model with validation, authentication and error handling.", "Add unit and integration tests, deployment automation and logs; investigate a performance or correctness issue.", "Prepare a code walkthrough and design discussion. Explain ownership, trade-offs and what you would improve."], "Build an authenticated booking API with concurrency handling, tests, a deployment pipeline and an operating guide.", [["How do you stop two users booking the same slot?", "Discuss database constraints, transactions, race conditions and a concurrency test."], ["How do you test an external dependency failure?", "Use controlled test doubles or an isolated service and verify timeout, retry and user-visible behaviour."]], ["aws/developer-associate", "microsoft/azure-ai-cloud-developer"], ["software developer", "software engineer", "backend", "full stack", "frontend"], "A strong code portfolio and interview fundamentals usually come first. Add a platform certification only when it matches the role; an AI-cloud credential is relevant to AI application jobs, not every developer vacancy."),
  path("cybersecurity", "Cybersecurity Analyst", "Security & Networks", "Turn alerts into evidence and a defensible response.", ["Networking", "Linux|Windows", "SIEM|Sentinel|Splunk", "Incident response", "Threat detection|MITRE ATT&CK", "Vulnerability|vulnerabilities", "IAM|identity", "Risk|security controls"], ["Review networks, operating systems, identity and common attack paths.", "Build a legal defensive lab and collect endpoint, identity and network logs.", "Investigate an alert, assess impact and document containment, recovery and evidence handling.", "Write a concise incident report with detection improvements and communicate risk to a non-technical stakeholder."], "Simulate a suspicious sign-in in an authorised lab and produce a triage timeline, detection query and response report.", [["How do you triage a suspicious login?", "Correlate identity, device, location and activity evidence; validate impact before taking proportionate action."], ["A critical vulnerability affects many systems. How do you prioritise?", "Consider exploitation, exposure, asset importance and compensating controls, then track remediation."]], ["comptia/security-plus", "microsoft/security-operations-analyst", "comptia/cysa-plus"], ["security analyst", "soc analyst", "cybersecurity", "security operations"]),
  path("network-engineer", "Network Engineer", "Security & Networks", "Explain packet paths, fault isolation and safe changes.", ["TCP/IP|TCP IP", "Routing|OSPF|BGP", "Switching|VLAN", "DNS|DHCP", "Firewall|ACL", "VPN", "Troubleshooting|packet capture", "Automation|Python|Ansible"], ["Practise subnetting, Ethernet, TCP/IP, DNS and DHCP.", "Configure VLANs, routing, access controls and connectivity in an authorised simulator or lab.", "Diagnose routing, MTU, DNS and firewall failures using packet evidence. Add basic configuration automation.", "Create a network diagram, change plan, validation checklist and rollback procedure."], "Build a segmented branch network with routing, VPN and monitoring; document three injected faults and their fixes.", [["A host can reach an IP but not its hostname. What next?", "Check resolver configuration, records, reachability and caching using reproducible tests."], ["How do you change a routing policy safely?", "Review impact, back up state, use a maintenance plan and validate routes and reachability with rollback ready."]], ["cisco/ccna", "comptia/network-plus", "cisco/ccnp-enterprise"], ["network engineer", "network administrator", "networking", "ccna", "ccnp"]),
  path("project-manager", "Project Manager", "Business & Delivery", "Show how you lead scope, risk and delivery decisions.", ["Project planning|schedule", "Stakeholders", "Risk management|risk register", "Budget|cost management", "Agile|Scrum", "Scope|requirements", "Delivery|milestones", "Communication|reporting"], ["Review project lifecycle, scope, delivery approaches and stakeholder needs.", "Build a charter, schedule, budget assumptions and risk register for a real or clearly labelled example project.", "Practise change control, dependency management, conflict resolution and reporting decisions.", "Prepare evidence-based stories about your leadership, outcomes and lessons; check certification eligibility honestly."], "Prepare a project pack with charter, milestones, RAID log, change request and a stakeholder status report.", [["The deadline is fixed but scope grows. How do you respond?", "Make trade-offs visible, assess impact and obtain an accountable decision on scope, time, cost and quality."], ["How do you handle a risk that becomes an issue?", "Assign ownership, activate a response, communicate impact and update the delivery plan."]], ["pmi/capm", "pmi/pmp", "pmi/pmi-acp"], ["project manager", "delivery manager", "program manager", "scrum master"], "CAPM is a foundation option. PMP is for candidates who meet PMI’s education, experience and training requirements. Your résumé cannot establish eligibility on its own; review the official requirements before applying."),
  path("business-leader", "AI Transformation Lead", "Business & Delivery", "Connect AI adoption to a measurable business problem.", ["AI strategy|AI adoption", "Business case|ROI", "Stakeholders", "Governance|responsible AI", "Change management", "Data readiness|data quality", "Risk management", "Metrics|KPIs"], ["Understand AI capabilities and limitations, then identify a specific business workflow.", "Assess data readiness, costs, risks and alternatives; define measurable pilot criteria.", "Design governance, human review and adoption support with named owners.", "Present a pilot decision with evidence, limitations and a plan for monitoring business outcomes."], "Write an AI pilot proposal with baseline measures, data checks, risk controls, adoption plan and go/no-go criteria.", [["How do you choose the first AI use case?", "Compare business value, feasibility, data readiness, risk and a simpler non-AI alternative."], ["A pilot is technically successful but users avoid it. What next?", "Investigate workflow fit, trust, training and incentives, then measure adoption and task outcomes."]], ["microsoft/ai-transformation-leader", "pmi/pmi-cpmai", "iapp/aigp"], ["ai transformation", "ai program manager", "ai governance", "ai product manager"]),
  path("crm-consultant", "Salesforce Consultant", "Business & Delivery", "Turn a business workflow into a usable Salesforce solution.", ["Salesforce", "Flow|automation", "Security|permission sets|sharing", "Data model|objects", "Reports|dashboards", "Requirements|business analysis", "Testing|UAT", "Integration|API"], ["Learn Salesforce objects, relationships, permissions and core sales/service workflows.", "Build a configured application with validation, Flow automation and reports.", "Plan data migration, access testing, integrations and error handling. Add Agentforce only after the platform foundations.", "Deliver a requirement-to-test traceability pack and demonstrate the solution to a business user."], "Build a lead-to-opportunity workflow in a developer environment with role-based access, Flow, reports and UAT cases.", [["Users see records they should not see. What do you inspect?", "Review object permissions, organisation-wide defaults, role hierarchy, sharing and permission assignments."], ["Would you choose Flow or code?", "Compare complexity, limits, maintainability, testing and the team’s operating capability."]], ["salesforce/platform-administrator", "salesforce/platform-app-builder", "salesforce/business-analyst", "salesforce/agentforce-specialist"], ["salesforce", "crm consultant", "salesforce administrator"]),
  path("qa-automation", "QA Automation Engineer", "Cloud & Engineering", "Build tests that catch real failures and support fast delivery.", ["Testing|test cases", "Automation|Playwright|Selenium|Cypress", "Programming|Java|TypeScript|Python", "API testing|Postman", "SQL", "CI/CD", "Defect|bug reporting", "Performance|accessibility"], ["Practise test design, boundary values, exploratory testing and clear defect reports.", "Build API and browser tests with controlled data, stable selectors and useful assertions.", "Integrate tests into CI and investigate flakiness. Cover security, accessibility or performance risks relevant to the product.", "Publish a test strategy, risk-based suite and one root-cause analysis of an escaped defect."], "Test a sample checkout flow with API and browser coverage, boundary cases, CI reports and a documented flaky-test fix.", [["How do you reduce a flaky test?", "Find the cause in timing, data, isolation or environment; replace blind waits with observable conditions."], ["What should you automate first?", "Prioritise repeatable, high-risk checks and keep exploratory testing for uncertainty."]], [], ["qa engineer", "test automation", "sdet", "quality assurance", "automation tester"], "Prioritise an automation portfolio. ISTQB CTFL can support testing foundations; verify its current syllabus and your local member-board exam route. It is optional and does not prove coding skill.", [{ label: "ISTQB certification information", url: "https://www.istqb.org/" }]),
  path("it-support", "IT Support Engineer", "Security & Networks", "Show calm troubleshooting and clear user communication.", ["Windows|macOS|Linux", "Hardware", "Networking|TCP/IP", "Microsoft 365|M365", "Active Directory|Entra ID", "Ticketing|ServiceNow|Jira", "Troubleshooting", "Security|MFA"], ["Practise operating systems, hardware, networks and common business applications.", "Learn account lifecycle, least privilege, MFA, endpoint setup and structured ticket notes.", "Diagnose login, connectivity and application incidents using safe, repeatable steps.", "Create a knowledge-base article and demonstrate escalation with evidence and user impact."], "Build a support lab and write five incident records covering account access, DNS, application errors, device setup and backup recovery.", [["A user cannot sign in. Where do you start?", "Verify identity through the approved process, establish scope and inspect account state, MFA and service health."], ["When do you escalate a ticket?", "Consider impact, permissions, time limits and evidence; communicate ownership and next steps."]], ["comptia/a-plus", "cisco/ccst-it-support", "comptia/network-plus"], ["it support", "service desk", "help desk", "desktop support"]),
  path("business-analyst", "Business Analyst", "Business & Delivery", "Make requirements clear enough to build and test.", ["Requirements|elicitation", "Stakeholders", "Process mapping|BPMN", "User stories", "Acceptance criteria", "SQL|data analysis", "Testing|UAT", "Agile|Scrum"], ["Practise stakeholder interviews, problem framing and current-state process mapping.", "Write prioritised requirements, user stories and measurable acceptance criteria.", "Validate options using data; manage changes, dependencies and requirement traceability.", "Prepare a workshop example, UAT plan and a story about resolving conflicting stakeholder needs."], "Analyse a returns process and deliver an as-is/to-be map, prioritised backlog, acceptance criteria and UAT pack.", [["Stakeholders disagree about a requirement. How do you proceed?", "Clarify the underlying needs, constraints and decision owner; compare options and document the agreement."], ["What makes an acceptance criterion useful?", "It describes observable behaviour with examples, boundaries and a clear pass/fail condition."]], ["pmi/pmi-pba", "salesforce/business-analyst", "scrum-org/psm-i"], ["business analyst", "functional analyst", "requirements analyst"], "PMI-PBA has experience requirements. Salesforce Business Analyst fits Salesforce roles specifically; PSM I covers Scrum knowledge, not a general business-analysis qualification."),
];
export const careerById = (id: string) => careerPaths.find(p => p.id === id);
export const pathCertifications = (path: CareerPath) => path.certs.map(key => certifications.find(c => certKey(c) === key)).filter((c): c is (typeof certifications)[number] => Boolean(c && isAvailable(c)));
export const careerGroups = ["All roles", ...new Set(careerPaths.map(p => p.group))];
export function jobBoardLinks(role: string, location = "India") {
  return [
    { name: "LinkedIn Jobs", url: `https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(role)}&location=${encodeURIComponent(location)}` },
    { name: "Indeed", url: `https://in.indeed.com/jobs?q=${encodeURIComponent(role)}&l=${encodeURIComponent(location)}` },
    { name: "Naukri", url: `https://www.naukri.com/${role.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}-jobs` },
  ];
}
