const { test } = require('node:test');
const assert = require('node:assert/strict');
const { receiveEnquiry } = require(process.env.ENQUIRY_TEST_BUILD + '/enquiry-handler.js');
const origin = 'https://www.globalcertsit.com';
const sample = () => ({ requestId:'a11b22c3-1234-4567-8910-123456789abc', startedAt:Date.now()-5000, name:'Integration Test', phone:'+1 202 555 0123', email:'test@example.com', certification:'AWS Solutions Architect', role:'Cloud Engineer', experience:'3–5 years', country:'United States', timeline:'Within 30 days', service:'Exam voucher pricing', consent:true, website:'', attribution:{utm_campaign:'global_certifications_website',password:'must-not-be-stored'} });
const request = (data = sample(), source = origin) => new Request(origin+'/api/enquiries',{method:'POST',headers:{origin:source,'Content-Type':'application/json'},body:JSON.stringify(data)});
function setup(overrides={}) { const rows=new Map(); return { rows, deps:{configured:true,production:true,origins:[origin],permit:()=>true,write:async(p,r)=>{if(rows.has(p))throw Error('Already exists');rows.set(p,r);},exists:async p=>rows.has(p),...overrides} }; }
test('success requires storage and returns only a receipt, never private answers or a blob URL',async()=>{const {rows,deps}=setup();const response=await receiveEnquiry(request(),deps);assert.equal(response.status,200);const result=await response.json();assert.deepEqual(Object.keys(result).sort(),['receiptId','received']);assert.equal(rows.size,1);const [path,record]=[...rows][0];assert.match(path,/^enquiries\/[a-f0-9-]+\.json$/);assert.equal(record.enquiry.phone,'+12025550123');assert.equal(record.enquiry.attribution.password,undefined);assert.equal(record.status,'new');});
test('lost-response retry preserves one enquiry and its receipt',async()=>{const {rows,deps}=setup();const data=sample();const first=await (await receiveEnquiry(request(data),deps)).json();const retry=await (await receiveEnquiry(request(data),deps)).json();assert.equal(rows.size,1);assert.equal(first.receiptId,retry.receiptId);});
test('storage failure never reports receipt',async()=>{const {deps}=setup({write:async()=>{throw Error('Unavailable')},exists:async()=>false});const response=await receiveEnquiry(request(),deps);assert.equal(response.status,503);assert.equal((await response.json()).received,undefined);});
test('cross-origin submissions cannot store enquiries',async()=>{const {rows,deps}=setup();assert.equal((await receiveEnquiry(request(sample(),'https://unrelated.example'),deps)).status,403);assert.equal(rows.size,0);});
test('invalid phone, missing consent and honeypot are rejected',async()=>{for(const change of [{phone:'9876543210'},{consent:false},{website:'spam'}]){const {rows,deps}=setup();assert.equal((await receiveEnquiry(request({...sample(),...change}),deps)).status,400);assert.equal(rows.size,0);}});
test('missing configuration and rate limits fail without claiming success',async()=>{for(const [overrides,status] of [[{configured:false},503],[{permit:()=>false},429]]){const {rows,deps}=setup(overrides);assert.equal((await receiveEnquiry(request(),deps)).status,status);assert.equal(rows.size,0);}});
test('oversized requests are rejected before storage',async()=>{const {rows,deps}=setup();assert.equal((await receiveEnquiry(request({...sample(),certification:'x'.repeat(13000)}),deps)).status,413);assert.equal(rows.size,0);});
test('preview verification is kept outside production enquiries',async()=>{const {rows,deps}=setup({production:false});assert.equal((await receiveEnquiry(request(),deps)).status,200);assert.match([...rows.keys()][0],/^verification\//);assert.equal([...rows.values()][0].environment,'verification');});
test('rate limit supplies a retry header',async()=>{const {deps,rows}=setup({permit:()=>({allowed:false,retryAfter:120})});const response=await receiveEnquiry(request(),deps);assert.equal(response.status,429);assert.equal(response.headers.get('Retry-After'),'120');assert.equal(rows.size,0);});
test('100 simultaneous independent enquiries get separate receipts',async()=>{const {randomUUID}=require('node:crypto');const {deps,rows}=setup();const responses=await Promise.all(Array.from({length:100},()=>receiveEnquiry(request({...sample(),requestId:randomUUID()}),deps)));assert.ok(responses.every(r=>r.status===200));assert.equal(rows.size,100);});
test('20 simultaneous retries store only one enquiry',async()=>{const {deps,rows}=setup();const data=sample();const responses=await Promise.all(Array.from({length:20},()=>receiveEnquiry(request(data),deps)));assert.ok(responses.every(r=>r.status===200));assert.equal(rows.size,1);});
