"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, BriefcaseBusiness, Check, FileSearch, Route, Search, Sparkles } from "lucide-react";
import { careerGroups, careerPaths } from "@/lib/career-paths";

export function CareerNav({ active }: { active: "paths" | "resume" | "jobs" }) {
  return <nav className="ch-subnav" aria-label="Career tools">{[{ id: "paths", title: "Role roadmaps", href: "/careers", Icon: Route }, { id: "resume", title: "Résumé review", href: "/careers/resume", Icon: FileSearch }, { id: "jobs", title: "Daily jobs", href: "/careers/jobs", Icon: BriefcaseBusiness }].map(({ id, title, href, Icon }) => <Link key={id} href={href} aria-current={active === id ? "page" : undefined}><Icon size={17}/>{title}</Link>)}</nav>;
}
export function CareerFeature() {
  return <section className="gc-container ch-home-feature"><div><span className="gc-kicker">NEW / YOUR CAREER SWITCH STARTS HERE</span><h2>A new role.<br/><span>A plan to get there.</span></h2><p>Choose your target role. Find the skills to prepare, the certifications to consider and the evidence your résumé needs.</p><Link href="/careers" className="gc-button gc-button-light">Build my career plan <ArrowUpRight size={18}/></Link></div><div className="ch-feature-steps">{[{ href: "/careers/sap-sd", label: "01 / PREPARE", title: "Explore the SAP SD roadmap", Icon: Route }, { href: "/careers/resume", label: "02 / IMPROVE", title: "Review your résumé", Icon: FileSearch }, { href: "/careers/jobs", label: "03 / APPLY", title: "Find your next opportunity", Icon: BriefcaseBusiness }].map(({ href, label, title, Icon }) => <Link href={href} key={href}><Icon size={25}/><div><small>{label}</small><strong>{title}</strong></div><ArrowUpRight size={18}/></Link>)}</div></section>;
}
export default function CareerHub() {
  const [query, setQuery] = useState("");
  const [group, setGroup] = useState("All roles");
  const paths = careerPaths.filter(p => (group === "All roles" || p.group === group) && `${p.title} ${p.search.join(" ")} ${p.skills.map(s => s.name).join(" ")}`.toLowerCase().includes(query.toLowerCase().trim()));
  return <main className="career-hub"><div className="gc-container"><CareerNav active="paths"/>
    <section className="ch-hero"><div><span className="gc-kicker"><Sparkles size={14}/> THE CAREER SWITCH HUB</span><h1>Your next role.<br/><em>Your next chapter.</em></h1><p>A job switch needs more than another certificate. Build a focused preparation plan, improve your résumé and find roles you can apply for.</p><div className="ch-actions"><a href="#role-paths" className="gc-button gc-button-light">Choose my target role <ArrowRight size={18}/></a><Link href="/careers/resume" className="gc-button gc-button-outline">Review my résumé <FileSearch size={18}/></Link></div><div className="ch-points"><span><Check size={14}/> {careerPaths.length} role roadmaps</span><span><Check size={14}/> No sign-up to explore</span></div></div>
      <div className="ch-orbit" aria-label="From your current skills to your next role"><div className="ch-orbit-ring"/><div className="ch-orbit-core"><Route size={37}/><span>YOUR NEXT</span><strong>MOVE.</strong></div><Link href="/careers/sap-sd" className="ch-orbit-card orbit-one"><small>EXPLORE THE ROADMAP</small><strong>SAP SD Consultant</strong><span>Skills → practice → certification <ArrowUpRight size={15}/></span></Link><Link href="/careers/resume" className="ch-orbit-card orbit-two"><FileSearch size={22}/><div><small>MAKE YOUR EXPERIENCE CLEAR</small><strong>Résumé review</strong></div></Link><Link href="/careers/jobs" className="ch-orbit-card orbit-three"><span className="ch-live-dot"/><div><small>REFRESHED DAILY</small><strong>Explore job listings ↗</strong></div></Link></div>
    </section>
    <section className="ch-module-strip">{[{ n: "01", title: "Know what to prepare", text: "Skills, practical projects and interview scenarios for your target role." }, { n: "02", title: "Show what you can do", text: "Résumé feedback and relevant certification options based on your target." }, { n: "03", title: "Make your next move", text: "Daily source listings and direct job-board searches with application links." }].map(s => <div key={s.n}><span>{s.n}</span><h2>{s.title}</h2><p>{s.text}</p></div>)}</section>
    <section className="ch-section" id="role-paths"><div className="ch-section-title"><div><span className="gc-kicker">START WITH THE ROLE YOU WANT</span><h2>Where do you want<br/>to go next?</h2></div><p>Choose a path to see preparation topics,<br/>certification guidance and interview practice.</p></div><div className="ch-search"><Search size={20}/><input aria-label="Search career roles" placeholder="Try SAP SD, Salesforce, Databricks, cloud…" value={query} onChange={e => setQuery(e.target.value)}/>{query && <button onClick={() => setQuery("")}>Clear</button>}</div><div className="ch-filters" aria-label="Career categories">{careerGroups.map(g => <button key={g} aria-pressed={group === g} onClick={() => setGroup(g)}>{g}</button>)}</div><p className="ch-result-count" role="status">{paths.length} role {paths.length === 1 ? "roadmap" : "roadmaps"}</p><div className="ch-role-grid">{paths.map((p, i) => <Link href={`/careers/${p.id}`} key={p.id} className={`ch-role-card ch-accent-${i % 4}`}><div><span>{p.group}</span><ArrowUpRight size={21}/></div><h3>{p.title}</h3><p>{p.tagline}</p><div className="ch-tags">{p.skills.slice(0, 3).map(s => <span key={s.name}>{s.name}</span>)}</div><footer>Open preparation roadmap <ArrowRight size={16}/></footer></Link>)}</div>{!paths.length && <div className="ch-empty"><h3>No matching roadmap yet.</h3><p>Try a broader role name or clear the filters. You can still search the job boards for any role.</p><button className="gc-button gc-button-outline" onClick={() => {setQuery(""); setGroup("All roles");}}>Show all roles</button></div>}</section>
    <div className="ch-note">Preparation plans are editorial guidance, not employer requirements or job guarantees. Use the exact vacancy and current official certification requirements to personalise your plan.</div>
  </div></main>;
}
