"use client";
import { useRef, useState } from "react";
import Link from "next/link";
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Check, Download, FilePenLine, FileSearch, LockKeyhole, Plus, Save, Trash2, Undo2, Upload } from "lucide-react";
import { careerPaths } from "@/lib/career-paths";
import { composeBullet, contactText, draftText, emptyDraft, parseResume, readDraft, type ResumeDraft } from "@/lib/resume-builder";
import { CareerNav } from "./CareerHub";

type Props = { draft: ResumeDraft; onChange: (draft: ResumeDraft) => void; onCheck: () => void; onBack: () => void };
export default function ResumeBuilder({ draft, onChange, onCheck, onBack }: Props) {
  const [history, setHistory] = useState<ResumeDraft[]>([]);
  const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [status, setStatus] = useState("");
  const [action, setAction] = useState(""); const [method, setMethod] = useState(""); const [result, setResult] = useState("");
  const resumeInput = useRef<HTMLInputElement>(null); const draftInput = useRef<HTMLInputElement>(null);
  const preview = useRef<HTMLElement>(null);
  const bullet = composeBullet(action, method, result);
  function change(next: ResumeDraft) {
    if (draftText(next).length > 60000) { setError("Keep your résumé below 60,000 characters."); return; }
    setHistory(h => [...h.slice(-29), draft]); onChange(next); setError(""); setStatus("");
  }
  function update(key: "name" | "headline" | "email" | "phone" | "location" | "links" | "targetRole" | "template", value: string) { change({ ...draft, [key]: value }); }
  function section(id: string, key: "title" | "content", value: string) { change({ ...draft, sections: draft.sections.map(s => s.id === id ? { ...s, [key]: value } : s) }); }
  function move(index: number, direction: number) { const next = [...draft.sections]; [next[index], next[index + direction]] = [next[index + direction], next[index]]; change({ ...draft, sections: next }); }
  function undo() { const last = history.at(-1); if (last) { onChange(last); setHistory(h => h.slice(0, -1)); setError(""); setStatus("Last change undone."); } }
  async function importFile(file: File | undefined, saved: boolean) {
    if (!file) return;
    if (draftText(draft) && !window.confirm("Replace the current résumé? You can use Undo to restore it.")) { if (draftInput.current) draftInput.current.value = ""; if (resumeInput.current) resumeInput.current.value = ""; return; }
    setBusy("import"); setError(""); setStatus("");
    try {
      if (saved && file.size > 200000) throw new Error("Choose a saved draft smaller than 200 KB.");
      const next = saved ? readDraft(await file.text()) : parseResume(await (await import("@/lib/resume-file")).extractResume(file), draft.targetRole);
      change(next); setStatus(saved ? "Saved draft opened. You can continue editing." : "Résumé imported. Check every section against the original text below.");
    } catch (e) { setError(e instanceof Error ? e.message : "We couldn’t open this file. Try PDF, DOCX or TXT."); }
    finally { setBusy(""); if (resumeInput.current) resumeInput.current.value = ""; if (draftInput.current) draftInput.current.value = ""; }
  }
  async function download(format: "pdf" | "docx" | "json" | "txt") {
    setError(""); setStatus("");
    if (format !== "json" && (!draft.name.trim() || !draft.sections.some(s => s.content.trim()))) { setError("Add your name and at least one section before downloading your résumé."); return; }
    setBusy(format);
    try {
      const { createPdf, createWord, resumeFilename, saveFile } = await import("@/lib/resume-export");
      const blob = format === "pdf" ? new Blob([new Uint8Array(await createPdf(draft))], { type: "application/pdf" }) : format === "docx" ? await createWord(draft) : new Blob([format === "json" ? JSON.stringify(draft, null, 2) : draftText(draft)], { type: format === "json" ? "application/json" : "text/plain;charset=utf-8" });
      saveFile(blob, `${resumeFilename(draft)}${format === "json" ? "-draft" : ""}.${format}`);
      setStatus(format === "json" ? "Draft download started. Keep this file to reopen and edit later." : `${format.toUpperCase()} download started. Check the finished document before applying.`);
    } catch (e) { setError(e instanceof Error ? e.message : "Download failed. Please try again."); }
    finally { setBusy(""); }
  }
  function insertBullet() {
    if (!bullet) return;
    const match = draft.sections.find(s => /experience/i.test(s.title));
    if (match) section(match.id, "content", `${match.content.trim()}\n- ${bullet}`.trim());
    else if (draft.sections.length < 20) change({ ...draft, sections: [...draft.sections, { id: crypto.randomUUID(), title: "Experience", content: `- ${bullet}` }] });
    else { setError("You can have up to 20 sections. Rename a section to Experience first."); return; }
    setStatus("Bullet added to Experience. Check that it accurately describes your work.");
  }
  return <main className="career-hub rb-workspace"><div className="gc-container"><CareerNav active="resume"/>
    <header className="ch-tool-hero rb-hero"><span className="gc-kicker"><FilePenLine size={15}/> RÉSUMÉ STUDIO</span><h1>Your experience.<br/><em>Ready for the next move.</em></h1><p>Create a résumé from scratch or improve the one you have. Edit every detail, check it against a target role and take it with you as PDF or Word.</p><div className="ch-privacy"><LockKeyhole size={17}/><span>The editor processes your résumé in this browser. Save a draft file to keep your changes after closing this page.</span></div></header>
    <div className="rb-mode-nav"><button className="rb-mode" onClick={onBack}><FileSearch size={18}/> Check résumé</button><span className="rb-mode rb-mode-active"><FilePenLine size={18}/> Create or edit résumé</span></div>
    <div className="rb-toolbar"><div><button className="gc-button gc-button-outline" disabled={!!busy} onClick={() => resumeInput.current?.click()}><Upload size={17}/> Import résumé</button><button className="gc-button gc-button-outline" disabled={!!busy} onClick={() => draftInput.current?.click()}>Open saved draft</button></div><div><button className="ch-inline-button" disabled={!!busy || !history.length} onClick={undo}><Undo2 size={16}/> Undo</button><button className="gc-button gc-button-outline" disabled={!!busy} onClick={() => void download("json")}><Save size={17}/> Save draft</button></div><input className="rb-file-input" ref={resumeInput} aria-label="Import résumé file" type="file" accept=".pdf,.docx,.txt" onChange={e => void importFile(e.target.files?.[0], false)}/><input className="rb-file-input" ref={draftInput} aria-label="Open résumé draft file" type="file" accept=".json" onChange={e => void importFile(e.target.files?.[0], true)}/></div>
    <div className="rb-feedback" aria-live="polite">{busy && <p className="ch-note">{busy === "import" ? "Reading your file…" : `Preparing your ${busy.toUpperCase()} file…`}</p>}{error && <p className="ch-error" role="alert">{error}</p>}{status && <p className="rb-status"><Check size={16}/>{status}</p>}</div>
    <div className="rb-layout"><section className="rb-editor" aria-label="Résumé editor"><fieldset disabled={!!busy}>
      <div className="rb-section-intro"><span className="gc-kicker">01 / MAKE IT YOURS</span><h2>Start with the essentials.</h2><p>Use details you can support. Leave anything unnecessary blank.</p></div>
      <div className="rb-fields"><label className="ch-field">Full name<input data-private="true" autoComplete="off" maxLength={120} value={draft.name} onChange={e => update("name", e.target.value)} placeholder="Your full name"/></label><label className="ch-field">Professional headline<input data-private="true" autoComplete="off" maxLength={180} value={draft.headline} onChange={e => update("headline", e.target.value)} placeholder="Your role or specialism"/></label><label className="ch-field">Email<input data-private="true" autoComplete="off" maxLength={200} type="email" value={draft.email} onChange={e => update("email", e.target.value)} placeholder="you@example.com"/></label><label className="ch-field">Phone<input data-private="true" autoComplete="off" maxLength={80} type="tel" value={draft.phone} onChange={e => update("phone", e.target.value)} placeholder="Include country code"/></label><label className="ch-field">Location<input data-private="true" autoComplete="off" maxLength={160} value={draft.location} onChange={e => update("location", e.target.value)} placeholder="City, country"/></label><label className="ch-field">LinkedIn / portfolio links<input data-private="true" autoComplete="off" maxLength={1000} value={draft.links} onChange={e => update("links", e.target.value)} placeholder="Full URLs, separated by a space or |"/></label></div>
      <label className="ch-field">Target role for your review<select value={draft.targetRole} onChange={e => update("targetRole", e.target.value)}><option value="">Choose a role for skill & certification guidance</option>{careerPaths.map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select></label><p className="ch-small">Your target role helps the review. It is not added to your résumé automatically.</p>
      <div className="rb-section-intro"><span className="gc-kicker">02 / SHOW YOUR EVIDENCE</span><h2>Experience that reads clearly.</h2><p>Keep each job title, employer and dates together. Start a line with “- ” for a bullet. Empty sections are left out of downloads.</p></div>
      {draft.sections.map((s, i) => <details className="rb-edit-section" key={s.id} open><summary>{s.title || "Untitled section"}<span>{s.content.trim() ? `${s.content.trim().split(/\s+/).length} words` : "Add details"}</span></summary><div className="rb-section-body"><label className="ch-field">Section title<input maxLength={100} value={s.title} onChange={e => section(s.id, "title", e.target.value)}/></label><label className="ch-field">{s.title || "Section"} content<textarea data-private="true" autoComplete="off" spellCheck rows={s.title === "Experience" ? 9 : 5} maxLength={60000} value={s.content} onChange={e => section(s.id, "content", e.target.value)} placeholder={s.title === "Certifications" ? "Credential name · Issuer · Date earned or expiry. Label in-progress learning clearly." : s.title === "Experience" ? "Job title · Employer · Dates\n- What you did, how you did it and a result you can support." : "Add your own details here."}/></label><div className="rb-section-controls"><button disabled={i === 0} onClick={() => move(i, -1)} aria-label={`Move ${s.title} up`}><ArrowUp size={16}/></button><button disabled={i === draft.sections.length - 1} onClick={() => move(i, 1)} aria-label={`Move ${s.title} down`}><ArrowDown size={16}/></button><button onClick={() => change({ ...draft, sections: draft.sections.filter(row => row.id !== s.id) })} aria-label={`Remove ${s.title}`}><Trash2 size={16}/> Remove</button></div></div></details>)}
      <button className="gc-button gc-button-outline rb-add" disabled={draft.sections.length >= 20} onClick={() => change({ ...draft, sections: [...draft.sections, { id: crypto.randomUUID(), title: "Additional information", content: "" }] })}><Plus size={17}/> Add section</button>
      <details className="rb-helper"><summary>Write a stronger experience bullet</summary><p>Build a sentence from your facts. Include an outcome only if you can support it.</p><label className="ch-field">What did you do?<input maxLength={500} value={action} onChange={e => setAction(e.target.value)} placeholder="Start with an action: built, resolved, configured…"/></label><label className="ch-field">Tools or method (optional)<input maxLength={500} value={method} onChange={e => setMethod(e.target.value)} placeholder="The tools or approach you actually used"/></label><label className="ch-field">Result or scale (optional)<input maxLength={500} value={result} onChange={e => setResult(e.target.value)} placeholder="A verified outcome; no invented numbers"/></label>{bullet && <blockquote>{bullet}</blockquote>}<button className="gc-button gc-button-outline" disabled={!bullet} onClick={insertBullet}>Add to Experience <Plus size={16}/></button></details>
      {draft.originalText && <details className="rb-original"><summary>Compare with original imported text</summary><p>Import groups recognised headings only. Review “Additional information” and move any misplaced text into the right section.</p><pre data-private="true">{draft.originalText}</pre></details>}
      <button className="ch-clear rb-reset" onClick={() => { if (!draftText(draft) || window.confirm("Start a blank résumé? You can use Undo to restore this draft.")) change(emptyDraft(draft.targetRole)); }}><Trash2 size={15}/> Start a blank résumé</button>
    </fieldset></section>
    <aside className="rb-preview-column"><div className="rb-preview-tools"><div><span className="gc-kicker">03 / READY TO SHARE</span><h2>Your live preview</h2></div><label className="ch-field">Style<select disabled={!!busy} value={draft.template} onChange={e => update("template", e.target.value)}><option value="modern">Modern navy</option><option value="classic">Classic black</option></select></label></div><p className="ch-small">Single column · Selectable text · Page breaks added in downloads</p>
      <article ref={preview} className={`rb-paper rb-paper-${draft.template}`} aria-label="Live résumé preview" data-private="true"><h2>{draft.name || "Your name"}</h2>{draft.headline && <p className="rb-paper-headline">{draft.headline}</p>}{contactText(draft) && <p className="rb-paper-contact">{contactText(draft)}</p>}{draft.sections.filter(s => s.content.trim()).map(s => <section key={s.id}><h3>{s.title}</h3>{s.content.split(/\r?\n/).filter(line => line.trim()).map((line, i) => /^\s*[-•*]\s+/.test(line) ? <p className="rb-paper-bullet" key={i}>{line.trim().replace(/^[-•*]\s+/, "")}</p> : <p key={i}>{line}</p>)}</section>)}{!draft.sections.some(s => s.content.trim()) && <div className="rb-paper-empty"><FilePenLine size={28}/><p>Your content will appear here as you type.<br/>Import a résumé or fill in the editor to begin.</p></div>}</article>
      <div className="rb-download-feedback">{error && <p className="ch-error">{error}</p>}{status && <p className="ch-small">{status}</p>}{busy && <p className="ch-small">Preparing your file…</p>}</div><div className="rb-export"><button className="gc-button gc-button-light" disabled={!!busy} onClick={() => void download("pdf")}><Download size={17}/> Download PDF</button><button className="gc-button gc-button-outline" disabled={!!busy} onClick={() => void download("docx")}><Download size={17}/> Download Word</button><button className="ch-inline-button" disabled={!!busy} onClick={() => void download("txt")}>Download plain text</button></div><button className="rb-review-cta" disabled={!!busy} onClick={() => { if (draftText(draft).length < 80) { setError("Add at least 80 characters before checking your draft."); return; } onCheck(); }}><FileSearch size={22}/><span><strong>Check this draft for my next role</strong><small>Skill mentions, improvements & certification options</small></span><ArrowRight size={19}/></button>
      <div className="rb-footnotes"><h3>Make every word count.</h3><p>Tailor your examples to the job description. List a certification as earned only when you hold it; label planned or in-progress learning clearly.</p><details><summary>How these résumé tools work</summary><p>The editor uses your text and facts. The reviewer checks readable text against a curated role checklist; it does not verify claims or predict an employer’s ATS score. Import can misplace sections, so compare with your original.</p><p>Our single-column exports and bullet helper follow guidance on clear formatting and action–project–result evidence from <a href="https://support.greenhouse.io/hc/en-us/articles/200989175-Unsuccessful-resume-parse" target="_blank" rel="noopener noreferrer">Greenhouse</a> and <a href="https://ocs.yale.edu/resources/writing-impactful-resume-bullets/" target="_blank" rel="noopener noreferrer">Yale Career Strategy</a>. Checked 13 September 2026. Employer requirements vary; follow the vacancy’s file instructions.</p><p>PDF supports Latin and extended Latin text. If a character is unsupported, use Word to preserve it. Saved draft files include your original imported text and personal information; keep them private.</p></details><Link href="/privacy">Privacy details <ArrowRight size={14}/></Link></div>
    </aside></div><button className="ch-inline-button rb-back" onClick={onBack}><ArrowLeft size={16}/> Back to résumé review</button>
  </div></main>;
}
