"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, ArrowUpRight, BookOpen, Check, FileSearch, MessageCircle } from "lucide-react";
import { pathCertifications, type CareerPath } from "@/lib/career-paths";
import { certUrl, whatsappUrl } from "@/lib/certifications";
import { CareerNav } from "./CareerHub";

export default function RoleRoadmap({ path }: { path: CareerPath }) {
  const [level, setLevel] = useState("switching");
  const [done, setDone] = useState<number[]>([]);
  const certs = pathCertifications(path);
  const phases = ["Build the foundations", "Practise the core work", "Handle real scenarios", "Prepare your evidence"];
  return <main className="career-hub"><div className="gc-container"><CareerNav active="paths"/><Link className="ch-back" href="/careers"><ArrowLeft size={15}/> All role roadmaps</Link>
    <header className="ch-role-hero"><div><span className="gc-kicker">{path.group} / CAREER ROADMAP</span><h1>{path.title}</h1><p>{path.tagline}</p><div className="ch-actions"><Link href={`/careers/resume?role=${path.id}`} className="gc-button gc-button-light">Check my résumé <FileSearch size={17}/></Link><Link href={`/careers/jobs?role=${path.id}`} className="gc-button gc-button-outline">Find relevant jobs <ArrowUpRight size={17}/></Link></div></div><div className="ch-route-stamp"><span>YOUR PREPARATION PATH</span><strong>Learn.<br/>Build.<br/><em>Make your move.</em></strong></div></header>
    <nav className="ch-anchor-nav" aria-label="Roadmap sections"><a href="#preparation">Preparation</a><a href="#credentials">Certifications</a><a href="#portfolio">Project & résumé</a><a href="#interviews">Interview practice</a></nav>
    <div className="ch-roadmap-layout"><div><section id="preparation" className="ch-section"><span className="gc-kicker">01 / GET READY FOR THE ROLE</span><h2>Your preparation plan.</h2><label className="ch-field ch-level">Your starting point<select value={level} onChange={e => setLevel(e.target.value)}><option value="switching">Switching from a related role</option><option value="starting">Starting in this field</option><option value="experienced">Experienced in this role</option></select></label><div className="ch-note ch-level-note">{level === "starting" ? "Work through all four stages. Give yourself time in an authorised practice environment and label your projects as learning work. Progress by demonstrated skills, not a promised number of weeks." : level === "experienced" ? "Use the first two stages as a gap check. Spend more time on complex failures, integration trade-offs, ownership and credible delivery stories. Match seniority to work you actually led." : "Map your existing experience to the skills below, then focus on the missing areas. Prepare two examples showing transferable problem-solving and clearly identify what you have practised versus delivered at work."}</div>
      <div className="ch-skill-list">{path.skills.map(s => <span key={s.name}>{s.name}</span>)}</div><div className="ch-progress"><span>{done.length} of 4 preparation stages checked</span><progress value={done.length} max={4} aria-label="Preparation progress"/></div><div className="ch-timeline">{path.topics.map((topic, i) => <article key={topic} className={done.includes(i) ? "is-done" : ""}><span className="ch-stage-number">{done.includes(i) ? <Check size={19}/> : `0${i + 1}`}</span><div><h3>{phases[i]}</h3><p>{topic}</p><label className="ch-checkbox"><input type="checkbox" checked={done.includes(i)} onChange={e => setDone(e.target.checked ? [...done, i] : done.filter(n => n !== i))}/> I can demonstrate this stage</label></div></article>)}</div><p className="ch-small">Your checklist stays in this page session only. It is a self-check, not a skills assessment.</p></section>
      <section className="ch-section" id="credentials"><span className="gc-kicker">02 / CHOOSE A RELEVANT GLOBAL CREDENTIAL</span><h2>Certify with a purpose.</h2><p>{path.credentialAdvice}</p><div className="ch-cert-list">{certs.map(c => <article key={c.id}><div><span className="ch-pill">{c.provider.toUpperCase()} · {c.level}{c.access && ` · ${c.access}`}</span><h3>{c.name}</h3><p>{c.why}</p><p className="ch-small"><b>Before booking:</b> {c.readiness}</p></div><Link href={certUrl(c)}>Details & registration <ArrowUpRight size={16}/></Link></article>)}</div>{path.learning.length > 0 && <div className="ch-source-links">{path.learning.map(l => <a key={l.url} href={l.url} target="_blank" rel="noopener noreferrer"><BookOpen size={16}/>{l.label}<ArrowUpRight size={15}/></a>)}</div>}<p className="ch-small">Review the official source for fees, assessment format, prerequisites and award/renewal requirements. Guidance reviewed 13 September 2026.</p></section>
      <section className="ch-section" id="portfolio"><span className="gc-kicker">03 / SHOW YOUR WORK</span><h2>Give your experience evidence.</h2><div className="ch-project"><span className="ch-pill">PRACTICE PROJECT</span><h3>A project you can explain.</h3><p>{path.project}</p></div><div className="ch-resume-tips"><h3>What your résumé should make clear</h3><ul><li>Your actual role, employment dates and the systems or business processes you worked on.</li><li>What you personally configured, built, investigated, tested or delivered.</li><li>A true outcome or scale, supported by evidence you can discuss without disclosing client information.</li><li>Credentials accurately marked as earned, expired or in progress. Keep lab work separate from employment.</li></ul><Link href={`/careers/resume?role=${path.id}`} className="gc-text-link">Review my résumé for this role <ArrowRight size={16}/></Link></div></section>
      <section className="ch-section" id="interviews"><span className="gc-kicker">04 / PRACTISE THE CONVERSATION</span><h2>Be ready to explain the “why”.</h2><p>Use these original practice scenarios to structure your answers. They are not leaked exam questions or an employer’s interview script.</p><div className="ch-interviews">{path.interviews.map(([q, a], i) => <details key={q}><summary><span>0{i + 1}</span>{q}</summary><p><b>A strong answer covers:</b> {a}</p></details>)}</div></section>
    </div><aside className="ch-plan-aside"><span className="gc-kicker">YOUR NEXT THREE STEPS</span><h2>Keep your switch focused.</h2><ol><li>Choose the skills you need to practise.</li><li>Improve your résumé with real evidence.</li><li>Compare vacancies and apply on the source site.</li></ol><Link href={`/careers/jobs?role=${path.id}`} className="gc-button gc-button-light">Explore jobs <ArrowUpRight size={16}/></Link><a href={whatsappUrl(`Hi Global Certs IT! I am planning a switch to ${path.title}. Please help me choose a relevant certification. My current role: . My experience: .`)} target="_blank" rel="noopener noreferrer" className="gc-button gc-button-outline"><MessageCircle size={17}/> Discuss my certification</a><p className="ch-small">You choose what to share on WhatsApp. Your résumé is not attached automatically.</p></aside></div>
  </div></main>;
}
