import Link from "next/link";
import { ArrowRight, ArrowUpRight, BadgeCheck, Check, ChevronDown, Compass, FileSearch, Globe2, Sparkles, Ticket, Zap } from "lucide-react";
import { certifications, providers, roles, isAvailable, whatsappUrl } from "@/lib/certifications";
import RoleIcon from "@/components/career/Icons";
import CertificationGlobe from "./CertificationGlobe";
import CertificationShowcase from "./CertificationShowcase";
import ProviderMark from "./ProviderMark";
import { CareerFeature } from "@/components/career/CareerHub";
import { ProviderDirectory, ClaudeSpotlight, CareerJourneys } from "./CatalogueExpansion";
import { WhatsAppIcon } from "./WhatsAppConcierge";
import CertificationUpdatesPreview from "./CertificationUpdatesPreview";

export default function CertificationHome() {
  const available = certifications.filter(c=>isAvailable(c));
  const featuredIds=["pmp","capm","pmi-acp","solutions-architect-associate","cloud-practitioner","azure-administrator","professional-cloud-architect","ai-practitioner","ai-business-strategist","fabric-data-engineer","professional-data-engineer","cissp","security-specialty","claude-associate-foundations","claude-developer-foundations","claude-architect-foundations","claude-architect-professional","agentforce-specialist","data-360-consultant","ccna","ccnp-enterprise","pmi-cpmai","pmi-rmp","aigp","cisa","cism","security-plus","cysa-plus","generative-ai-engineer","context-engineer"];
  const featured=featuredIds.map(id=>available.find(c=>c.id===id)).filter((c):c is typeof certifications[number]=>Boolean(c));
  const brands=["pmi","aws","microsoft","google-cloud","cisco","salesforce","snowflake","databricks","anthropic","comptia","iapp","isaca"];
  return <main className="gc-experience">
    <section className="gc-hero">
      <div className="hero-aurora aurora-one" aria-hidden="true"/><div className="hero-aurora aurora-two" aria-hidden="true"/><div className="hero-starfield" aria-hidden="true"/>
      <div className="gc-container gc-hero-layout">
        <div className="gc-hero-copy"><span className="gc-kicker hero-hello"><span className="kicker-line"/> YOUR AMBITION HAS NO BORDERS</span>
          <h1>Global IT<br/><span className="hero-gradient">Certifications.</span></h1><h2>Your next career move.</h2>
          <p className="gc-hero-description">PMP, Claude, AWS, Microsoft, Salesforce and more.<br/>Get certification guidance, exam details and voucher support—all in one place.</p>
          <div className="gc-hero-actions"><a className="gc-button gc-button-whatsapp" href={whatsappUrl("Hi Global Certs IT! I am interested in a global certification. Please share the price and payment details.")} target="_blank" rel="noopener noreferrer"><WhatsAppIcon size={22}/> Get price on WhatsApp <ArrowUpRight size={19}/></a><Link className="gc-button gc-button-outline" href="/certifications/explore">Explore all certifications <ArrowRight size={18}/></Link></div>
          <div className="hero-resume-entry"><Link href="/careers/resume"><FileSearch size={19}/><span><strong>Check & improve your résumé</strong><small>Create · Edit · Download PDF / Word</small></span><ArrowUpRight size={18}/></Link></div>
          <div className="hero-assurance"><span><Check size={14}/> Personal guidance</span><span><Check size={14}/> Telugu & English</span><span><Check size={14}/> No sign-up</span></div>
          <div className="hero-fast-links"><span>START HERE</span><Link href="/certifications/pmi/pmp">PMP <ArrowUpRight size={12}/></Link><Link href="/certifications/aws">AWS <ArrowUpRight size={12}/></Link><Link href="/certifications/microsoft">Microsoft <ArrowUpRight size={12}/></Link><Link href="/certifications/anthropic">Claude <Sparkles size={12}/></Link><a href="#providers">All providers <ArrowUpRight size={12}/></a></div>
        </div>
        <CertificationGlobe/>
      </div>
      <div className="gc-container hero-stat-strip"><div><strong>{available.length}<span>+</span></strong><span>certifications to explore</span></div><div><strong>{providers.length}</strong><span>global certification providers</span></div><div><strong>{roles.length}</strong><span>career paths to discover</span></div><a href="#certifications"><span>FIND YOUR NEXT CERTIFICATION</span><span className="scroll-circle"><ChevronDown size={20}/></span></a></div>
    </section>
    <section className="provider-ribbon" aria-label="Browse certification providers"><div className="ribbon-label">GLOBAL CERTIFICATIONS.<br/><strong>EXCEPTIONAL POSSIBILITIES.</strong></div><div className="ribbon-viewport"><div className="ribbon-track">{[0,1].map(copy=><div className="ribbon-group" key={copy} aria-hidden={copy===1 ? true : undefined}>{brands.map(id=><Link key={id} href={`/certifications/${id}`} tabIndex={copy===1 ? -1 : undefined} aria-label={`Explore ${providers.find(p=>p.id===id)?.name} certifications`}><ProviderMark provider={id}/></Link>)}</div>)}</div></div></section>
    <section id="certifications" className="gc-container gc-section certifications-section"><div className="gc-section-heading"><div><span className="gc-kicker"><BadgeCheck size={15}/> GLOBAL CERTIFICATIONS, FRONT AND CENTRE</span><h2>Big goals.<br/><span>Recognised certifications.</span></h2></div><p>Know your exam? Go straight to the details.<br/>Still deciding? Find the certification that fits you.</p></div><CertificationShowcase items={featured}/></section>
    <CertificationUpdatesPreview/>
    <ProviderDirectory/>
    <ClaudeSpotlight/>
    <section className="gc-container pmp-section"><div className="pmp-feature-panel"><div className="pmp-feature-copy"><span className="gc-kicker"><BadgeCheck size={15}/> PROJECT MANAGEMENT PROFESSIONAL</span><h2>Experience leads.<br/><span>PMP makes it recognised.</span></h2><p>Turn your project management experience into a clear certification plan. Understand eligibility, the application and your next exam steps.</p><div className="pmp-benefits"><span><Check size={15}/> Eligibility guidance</span><span><Check size={15}/> Application information</span><span><Check size={15}/> Exam & voucher enquiries</span></div><a className="gc-button gc-button-light" href={whatsappUrl("Hi Global Certs IT! I am interested in PMP certification. Please share the price and payment details.")} target="_blank" rel="noopener noreferrer"><WhatsAppIcon/> Get PMP price <ArrowUpRight size={18}/></a><Link href="/certifications/pmi/pmp" className="pmp-details-link">Read PMP certification details <ArrowRight size={15}/></Link></div><div className="pmp-badge-scene" aria-hidden="true"><div className="pmp-halo"/><div className="pmp-credential"><span>PROJECT MANAGEMENT INSTITUTE</span><div className="pmp-laurel"><BadgeCheck size={49} strokeWidth={1.15}/></div><strong>PMP<sup>®</sup></strong><b>PROJECT MANAGEMENT<br/>PROFESSIONAL</b><i/><small>LEAD PROJECTS. BUILD YOUR FUTURE.</small></div><div className="pmp-plinth"/></div></div></section>
    <section className="gc-container gc-section role-section"><div className="gc-section-heading"><div><span className="gc-kicker"><Compass size={15}/> NOT SURE WHICH CERTIFICATION TO CHOOSE?</span><h2>Your role.<br/><span>Your certification path.</span></h2></div><p>Choose your career direction. Compare relevant<br/>certifications by experience and technology.</p></div><div className="gc-role-grid">{["project-manager","cloud-engineer","data-engineer","ai-engineer","cybersecurity","data-analyst"].map((id,i)=>{const role=roles.find(r=>r.id===id)!; return <Link href={`/certifications?role=${id}`} className={`gc-role-card role-color-${i}`} key={id}><span className="gc-role-icon"><RoleIcon name={role.icon} size={26}/></span><h3>{role.name}</h3><p>{role.description}</p><span className="gc-role-bottom">{available.filter(c=>c.roles[role.id]).length} certification options <ArrowUpRight size={17}/></span></Link>;})}</div><Link href="/certifications" className="gc-text-link">Explore all {roles.length} career paths <ArrowRight size={16}/></Link></section>
    <section className="gc-container ai-spotlight-section"><div className="ai-spotlight"><div className="ai-artwork" aria-hidden="true"><div className="ai-orbit ai-orbit-a"/><div className="ai-orbit ai-orbit-b"/><div className="ai-crystal"><Sparkles size={75} strokeWidth={1}/></div><span className="ai-art-tag"><Zap size={13}/> THE NEXT CHAPTER IS AI</span></div><div className="ai-spotlight-copy"><span className="gc-kicker"><Sparkles size={15}/> AI & GENERATIVE AI CERTIFICATIONS</span><h2>Be ready for<br/><span>what comes next.</span></h2><p>Starting with AI, building intelligent apps, or leading AI adoption? Discover a certification path for your level of experience.</p><div className="ai-stage-pills"><span>01 · Start with AI</span><span>02 · Build with AI</span><span>03 · Lead with AI</span></div><Link className="gc-button gc-button-outline" href="/ai-certifications">Explore AI certifications <ArrowUpRight size={18}/></Link></div></div></section>
    <section className="gc-container gc-section gc-how-section"><div className="gc-section-heading"><div><span className="gc-kicker">SIMPLE FROM YOUR VERY FIRST CLICK</span><h2>From “which exam?”<br/><span>to a clear next step.</span></h2></div><p>Get the information you need<br/>before you make a decision.</p></div><div className="gc-how-grid">{[{icon:<Globe2/>,title:"Choose your certification",text:"Browse PMP, cloud, AI, data and security certifications—or start with your role."},{icon:<MessageIcon/>,title:"Message us on WhatsApp",text:"Tell us the exam, your country and target date. Your selected certification is added to the message."},{icon:<Ticket/>,title:"Get pricing & book",text:"Review eligibility and registration on the website, then request the price and payment details on WhatsApp."}].map((step,i)=><article key={step.title}><span className="how-top"><span>{step.icon}</span><b>0{i+1}</b></span><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></section>
    <CareerFeature/>
    <CareerJourneys/>
    <section className="gc-container gc-faq-section"><div><span className="gc-kicker">QUICK ANSWERS</span><h2>Clear before<br/><span>you commit.</span></h2><a href={whatsappUrl("Hi Global Certs IT! I am interested in a global certification. Please share the price and payment details.")} target="_blank" rel="noopener noreferrer" className="gc-text-link">Ask us on WhatsApp <ArrowUpRight size={16}/></a></div><div className="gc-faq-list">{[{q:"What can Global Certs IT help me with?",a:"Compare global certifications, preparation topics, eligibility and registration steps on our website. When you are ready to book, use WhatsApp for pricing and payment details."},{q:"I’m confused between AWS, Azure and Google Cloud. Where do I start?",a:"Start with your current role and the cloud platform used by your team or target jobs. Our certification finder lets you filter by role, experience and provider, then compare your options."},{q:"Can I contact you directly about PMP?",a:"Read the PMP eligibility and application guidance on its certification page. Use WhatsApp when you are ready to ask for pricing and payment details."},{q:"Does a certification guarantee a job or an exam pass?",a:"No. A certification can validate knowledge and skills, but exam results and career outcomes depend on your preparation, experience and other factors. Always check the official provider requirements before booking."}].map(item=><details key={item.q}><summary>{item.q}<span>+</span></summary><p>{item.a}</p></details>)}</div></section>
    <section className="gc-final-cta"><div className="final-orbit" aria-hidden="true"/><div className="gc-container"><span className="gc-kicker">ONE MESSAGE. A CLEARER NEXT STEP.</span><h2>Let’s talk about<br/><span>your next certification.</span></h2><p>Claude · PMP · Salesforce · Databricks · Cisco · ISACA · CompTIA · AIGP</p><a className="gc-button gc-button-whatsapp" href={whatsappUrl("Hi Global Certs IT! I am interested in a global certification. Please share the price and payment details.")} target="_blank" rel="noopener noreferrer"><WhatsAppIcon size={23}/> Chat on WhatsApp <ArrowUpRight size={20}/></a><span className="final-phone">+91 93928 28155 <i/> Telugu & English</span></div></section>
  </main>;
}
function MessageIcon(){return <WhatsAppIcon size={24}/>;}
