import Link from "next/link";
import { ArrowRight, ArrowUpRight, BadgeCheck, BookOpen, BriefcaseBusiness, CalendarDays, Check, Cloud, Compass, FileCheck2, FilePenLine, FileSearch, GraduationCap, Layers3, Search, ShieldCheck, Sparkles, Ticket, Workflow } from "lucide-react";
import { certifications, providers, roles, isAvailable, whatsappUrl, type Certification } from "@/lib/certifications";
import { filterCatalogue, orderedProviders } from "@/lib/catalogue";
import { certificationUpdates } from "@/lib/certification-updates";
import CertificationShowcase, { type HomeCert } from "./CertificationShowcase";
import ProviderMark from "./ProviderMark";
import { WhatsAppIcon } from "./WhatsAppConcierge";

const homeFields = [
  { label: "Popular picks", category: "All fields" },
  { label: "Cloud", category: "Cloud" },
  { label: "AI", category: "AI" },
  { label: "PMP & Agile", category: "Project Management & Agile" },
  { label: "Security", category: "Cybersecurity" },
  { label: "Business apps", category: "Business Apps & Automation" },
];
const toCard = (c: Certification): HomeCert => ({ id: c.id, provider: c.provider, name: c.name, exam: c.exam, level: c.level, why: c.why, skills: c.skills.slice(0, 2), access: c.access, status: c.status });

export default function CertificationHome() {
  const available = certifications.filter(c => isAvailable(c));
  const groups = homeFields.map(field => ({ ...field, items: filterCatalogue(available, { category: field.category }).slice(0, 6).map(toCard), href: field.category === "All fields" ? "/certifications/explore" : `/certifications/explore?category=${encodeURIComponent(field.category)}#all-certifications` }));
  const brands = ["aws", "microsoft", "google-cloud", "salesforce", "servicenow", "cisco"];
  const paths = [
    { id: "project-manager", title: "Lead projects", detail: "PMP, agile delivery & programme management", Icon: BriefcaseBusiness, color: "violet" },
    { id: "cloud-engineer", title: "Build in the cloud", detail: "AWS, Azure & Google Cloud", Icon: Cloud, color: "blue" },
    { id: "data-engineer", title: "Work with data", detail: "Pipelines, lakehouses & analytics", Icon: Layers3, color: "mint" },
    { id: "cybersecurity", title: "Secure what matters", detail: "Security operations, risk & governance", Icon: ShieldCheck, color: "peach" },
  ] as const;
  return <main className="hp-home">
    <section className="hp-hero" aria-labelledby="home-title">
      <div className="hp-hero-grid hp-wrap">
        <div className="hp-hero-copy"><span className="hp-eyebrow"><i/> GLOBAL CERTS IT · MADE FOR YOUR NEXT MOVE</span><h1 id="home-title">Global certifications.<br/><em>Personal guidance.</em></h1><p>Find your certification, understand the exam and get voucher guidance. A clear next step for your professional growth.</p><div className="hp-hero-actions"><Link className="hp-button hp-button-mint" href="/certifications/explore">Explore all certifications <ArrowUpRight size={19}/></Link><a className="hp-button hp-button-outline" href={whatsappUrl("Hi Global Certs IT! I would like exam pricing and voucher details.")} target="_blank" rel="noopener noreferrer"><WhatsAppIcon size={19}/> Get exam pricing</a></div><div className="hp-hero-assurance"><span><Check size={14}/> Telugu & English</span><span><Check size={14}/> Personal support</span><span><Check size={14}/> Browse without sign-up</span></div>
          <form action="/certifications/explore" method="get" className="hp-search" role="search"><label htmlFor="home-exam-search">Know your exam? Find it here.</label><div><Search size={20}/><input id="home-exam-search" type="search" name="q" placeholder="PMP, AZ-104, ServiceNow, ISTQB…" aria-label="Search certification exams" required/><button type="submit" aria-label="Search certifications"><ArrowRight size={20}/></button></div></form>
          <nav className="hp-fast-links" aria-label="Quick certification links"><Link href="/certifications/pmi/pmp">PMP <ArrowUpRight size={12}/></Link><Link href="/certifications/explore?provider=aws#all-certifications">AWS <ArrowUpRight size={12}/></Link><Link href="/certifications/explore?provider=microsoft#all-certifications">Microsoft <ArrowUpRight size={12}/></Link><Link href="/certifications/explore?provider=servicenow#all-certifications">ServiceNow <ArrowUpRight size={12}/></Link></nav>
        </div>
        <div className="hp-hero-visual">
          <div className="hp-orbit hp-orbit-a" aria-hidden="true"/><div className="hp-orbit hp-orbit-b" aria-hidden="true"/><div className="hp-orbit-dot" aria-hidden="true"/>
          <div className="hp-visual-caption"><span>YOUR EXPERIENCE. YOUR NEXT CHAPTER.</span><Compass size={19}/></div>
          <Link className="hp-hero-pmp" href="/certifications/pmi/pmp" aria-label="Explore PMP certification and eligibility"><div className="hp-pmp-top"><ProviderMark provider="pmi"/><span>PROJECT LEADERSHIP</span></div><div className="hp-pmp-centre"><div><span>MAKE YOUR EXPERIENCE COUNT</span><strong>PMP<sup>®</sup></strong><p>Project Management<br/>Professional</p></div><BriefcaseBusiness size={77} strokeWidth={1}/></div><div className="hp-pmp-bottom"><span>Eligibility · Application · Exam guidance</span><span><ArrowUpRight size={20}/></span></div></Link>
          <div className="hp-cloud-pair"><Link href="/certifications/explore?provider=aws#all-certifications"><ProviderMark provider="aws"/><span>Build your cloud path.</span><ArrowUpRight size={18}/></Link><Link href="/certifications/explore?provider=microsoft#all-certifications"><ProviderMark provider="microsoft"/><span>Azure. Fabric. AI.</span><ArrowUpRight size={18}/></Link></div>
          <Link className="hp-visual-resume" href="/careers/resume"><span><FileCheck2 size={23}/></span><div><strong>Make your experience stand out.</strong><small>Explore your résumé tools</small></div><ArrowUpRight size={17}/></Link>
        </div>
      </div>
      <div className="hp-wrap hp-hero-bottom"><div><strong>{available.length}</strong><span>certifications to explore</span></div><div><strong>{providers.length}</strong><span>global providers</span></div><div><strong>{roles.length}</strong><span>career paths</span></div><a href="#certifications">Find your next certification <ArrowRight size={18}/></a></div>
    </section>
    <section className="hp-brand-strip hp-wrap" aria-label="Explore leading certification providers"><span>ONE PLACE.<br/><strong>GLOBAL POSSIBILITIES.</strong></span><div>{brands.map(id => <Link key={id} href={`/certifications/explore?provider=${id}#all-certifications`} aria-label={`Browse ${providers.find(p => p.id === id)?.name} certifications`}><ProviderMark provider={id}/></Link>)}</div></section>
    <section className="hp-wrap hp-start" aria-label="Choose how we can help"><Link href="/certifications"><span className="hp-start-icon hp-violet"><Compass size={23}/></span><div><h2>Find my certification</h2><p>Start with your role and experience.</p></div><ArrowUpRight size={19}/></Link><Link href="/careers/resume"><span className="hp-start-icon hp-mint"><FileSearch size={23}/></span><div><h2>Check my résumé</h2><p>Review, improve and build your profile.</p></div><ArrowUpRight size={19}/></Link><Link href="/careers"><span className="hp-start-icon hp-blue"><BriefcaseBusiness size={23}/></span><div><h2>Plan my career move</h2><p>Explore role roadmaps and job listings.</p></div><ArrowUpRight size={19}/></Link></section>
    <section className="hp-wrap hp-section" id="certifications" aria-labelledby="home-certifications-title"><div className="hp-heading"><div><span className="hp-eyebrow">GLOBAL CREDENTIALS. PRACTICAL NEXT STEPS.</span><h2 id="home-certifications-title">Your next certification,<br/><em>closer than you think.</em></h2></div><p>Start with a popular option or explore your field.<br/>Check the details. Ask us about pricing.</p></div><CertificationShowcase groups={groups}/></section>
    <section className="hp-wrap hp-section hp-paths" id="career-journeys" aria-labelledby="home-paths-title"><div className="hp-heading"><div><span className="hp-eyebrow">START WITH WHAT YOU WANT TO DO</span><h2 id="home-paths-title">Your role sets the direction.</h2></div><Link href="/certifications">Explore all {roles.length} career paths <ArrowUpRight size={18}/></Link></div><div className="hp-path-grid">{paths.map(path => <Link key={path.id} href={`/certifications?role=${path.id}`} className={`hp-path hp-${path.color}`}><span><path.Icon size={27}/><small>{available.filter(c => c.roles[path.id]).length} options</small></span><h3>{path.title}</h3><p>{path.detail}</p><span>Find my path <ArrowUpRight size={17}/></span></Link>)}</div></section>
    <section className="hp-wrap hp-section" id="career-tools" aria-labelledby="career-tools-title"><div className="hp-toolkit"><div className="hp-toolkit-copy"><span className="hp-eyebrow">YOUR CAREER TOOLKIT</span><h2 id="career-tools-title">The credential is one part.<br/><em>Build the whole profile.</em></h2><p>Bring your experience, skills and next move together. Use our résumé and career tools to turn your plans into something practical.</p><Link className="hp-button hp-button-mint" href="/careers/resume"><FileSearch size={19}/> Check my résumé <ArrowUpRight size={18}/></Link><span className="hp-toolkit-note">Your résumé is processed in your browser.</span><div className="hp-profile-art" aria-hidden="true"><div className="hp-profile-top"><FileCheck2 size={28}/><span>YOUR PROFESSIONAL PROFILE</span><BadgeCheck size={23}/></div><div className="hp-profile-row"><span>Experience</span><b>Make your contribution clear.</b><Check size={16}/></div><div className="hp-profile-row"><span>Skills</span><b>Show what you can do.</b><Check size={16}/></div><div className="hp-profile-row"><span>Next step</span><b>Connect skills to a career path.</b><Check size={16}/></div></div></div><div className="hp-toolkit-links">{[{ icon: FileSearch, number: "01", title: "Review your résumé", copy: "Get feedback and identify areas to improve.", href: "/careers/resume" }, { icon: FilePenLine, number: "02", title: "Build a stronger résumé", copy: "Create, edit and export your professional profile.", href: "/careers/resume-builder" }, { icon: Workflow, number: "03", title: "Plan your career switch", copy: "Explore role roadmaps, skills and certification paths.", href: "/careers" }, { icon: BriefcaseBusiness, number: "04", title: "Explore job opportunities", copy: "Browse listings and check the application details.", href: "/careers/jobs" }].map(tool => <Link href={tool.href} key={tool.number}><span className="hp-tool-number">{tool.number}</span><tool.icon size={25}/><div><h3>{tool.title}</h3><p>{tool.copy}</p></div><ArrowUpRight size={20}/></Link>)}</div></div></section>
    <section className="hp-wrap hp-section hp-providers" id="providers" aria-labelledby="home-providers-title"><div className="hp-heading"><div><span className="hp-eyebrow">FIND YOUR PLATFORM</span><h2 id="home-providers-title">Global names.<br/><em>One place to begin.</em></h2></div><Link href="/certifications/explore#certification-providers">Browse all {providers.length} providers <ArrowUpRight size={18}/></Link></div><div className="hp-provider-grid">{[...orderedProviders.slice(0, 10), ...orderedProviders.filter(p => ["istqb", "sap"].includes(p.id))].map(p => <Link href={`/certifications/explore?provider=${p.id}#all-certifications`} key={p.id}><ProviderMark provider={p.id}/><span>{available.filter(c => c.provider === p.id).length} certifications<ArrowUpRight size={16}/></span></Link>)}</div><p className="hp-provider-more">Also explore <Link href="/certifications/explore?provider=peoplecert#all-certifications">PeopleCert</Link>, <Link href="/certifications/explore?provider=safe#all-certifications">SAFe</Link>, <Link href="/certifications/explore?provider=oracle#all-certifications">Oracle</Link>, <Link href="/certifications/explore?provider=fortinet#all-certifications">Fortinet</Link> and more in the complete directory.</p></section>
    <section className="hp-wrap hp-section" aria-labelledby="home-ai-title"><div className="hp-ai-band"><div className="hp-ai-symbol" aria-hidden="true"><Sparkles size={50} strokeWidth={1.2}/></div><div><span className="hp-eyebrow">BUILD FOR WHAT’S NEXT</span><h2 id="home-ai-title">AI is changing your field.<br/>Find your place in it.</h2><p>Explore AI certifications for builders, analysts and business leaders.</p></div><Link className="hp-button hp-button-outline" href="/ai-certifications">Explore AI pathways <ArrowUpRight size={18}/></Link></div></section>
    <section className="hp-wrap hp-section hp-support" aria-labelledby="home-support-title"><div className="hp-heading"><div><span className="hp-eyebrow">PERSONAL GUIDANCE, FROM THE FIRST QUESTION</span><h2 id="home-support-title">Know the steps.<br/><em>Make a confident choice.</em></h2></div><p>Get clarity before you book.<br/>Talk to us in Telugu or English.</p></div><div className="hp-support-grid">{[{ Icon: Compass, title: "Choose your certification", copy: "Compare relevant exams, skills and eligibility. Start with your role if you’re unsure.", step: "01" }, { Icon: Ticket, title: "Ask about your exam", copy: "Get current pricing, voucher availability and booking information directly on WhatsApp.", step: "02" }, { Icon: BookOpen, title: "Plan your preparation", copy: "Review the official exam objectives, registration steps and preparation guidance.", step: "03" }].map(step => <article key={step.step}><div><step.Icon size={26}/><span>{step.step}</span></div><h3>{step.title}</h3><p>{step.copy}</p></article>)}</div><div className="hp-support-footer"><span><ShieldCheck size={18}/> Official provider sources linked in certification details.</span><Link href="/contact">Meet your next step with personal support <ArrowUpRight size={16}/></Link></div></section>
    <section className="hp-wrap hp-section hp-updates" aria-labelledby="home-updates-title"><div><span className="hp-eyebrow"><CalendarDays size={16}/> STAY IN THE KNOW</span><h2 id="home-updates-title">Before you book,<br/>check what’s changing.</h2><Link href="/certification-updates">View certification updates <ArrowUpRight size={17}/></Link></div><div>{certificationUpdates.filter(u => !u.endsAt).slice(0, 3).map(update => <Link href={`/certification-updates#${update.id}`} key={update.id}><div><span>{update.provider}</span><h3>{update.title}</h3><p>{update.dateLabel}</p></div><ArrowUpRight size={20}/></Link>)}</div></section>
    <section className="hp-wrap hp-section hp-faq" aria-labelledby="home-faq-title"><div><span className="hp-eyebrow">LET’S MAKE IT CLEAR</span><h2 id="home-faq-title">Questions?<br/>Start here.</h2><p>Need an answer for your specific exam?</p><a href={whatsappUrl("Hi Global Certs IT! I have a question about a certification.")} target="_blank" rel="noopener noreferrer"><WhatsAppIcon size={19}/> Ask us on WhatsApp <ArrowUpRight size={17}/></a></div><div>{[{ q: "What can Global Certs IT help me with?", a: "We help you explore certifications, understand eligibility and registration, and enquire about exam vouchers and preparation guidance. You can also use our résumé and career-planning tools." }, { q: "Can I take my certification exam from home?", a: "It depends on the exact certification, exam provider and country. Many exams offer online proctoring; others require a test centre, a course or a practical assessment. Check the certification details and confirm the available mode before booking." }, { q: "How do I get the price for an exam?", a: "Choose your certification and tap Enquire on WhatsApp. The message includes the exam name so we can discuss current pricing, voucher availability and the booking steps directly." }, { q: "I’m not sure which certification to choose. Where do I start?", a: "Use Find my certification to explore options for your role and experience. Focus on the technology used in your work or target role, then compare skills, level and eligibility." }].map(f => <details key={f.q}><summary>{f.q}<span>+</span></summary><p>{f.a}</p></details>)}</div></section>
    <section className="hp-wrap hp-section hp-final"><div><span className="hp-eyebrow">YOUR NEXT CHAPTER STARTS WITH A CONVERSATION</span><h2>You bring the ambition.<br/><em>Let’s plan the next step.</em></h2><p>Certification guidance, exam vouchers and a clearer path forward.</p><div><a className="hp-button hp-button-mint" href={whatsappUrl("Hi Global Certs IT! Please help me with my next certification.")} target="_blank" rel="noopener noreferrer"><WhatsAppIcon size={21}/> Talk to Global Certs IT <ArrowUpRight size={19}/></a><span>+91 93928 28155<br/><small>Telugu & English</small></span></div></div><div className="hp-final-art" aria-hidden="true"><GraduationCap size={76} strokeWidth={1}/><span>YOUR NEXT<br/><b>BIG MOVE.</b></span></div></section>
  </main>;
}
